// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDowPQjgrSe4KzrBQCGYzQwTrDbNwQXBus',
    appId: '1:974085623091:web:5d66148f95bc4f68520246',
    messagingSenderId: '974085623091',
    projectId: 'speezyyeni',
    authDomain: 'speezyyeni.firebaseapp.com',
    storageBucket: 'speezyyeni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4XjANY3WYbrjiohjXXsKo2G2orwJudc',
    appId: '1:974085623091:android:e5b6432861c4a1d0520246',
    messagingSenderId: '974085623091',
    projectId: 'speezyyeni',
    storageBucket: 'speezyyeni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGEU7LUHMqSChGnzTZbkq7lkhc0yd96Yk',
    appId: '1:974085623091:ios:9b01dac4de3616ed520246',
    messagingSenderId: '974085623091',
    projectId: 'speezyyeni',
    storageBucket: 'speezyyeni.firebasestorage.app',
    iosBundleId: 'com.example.speezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGEU7LUHMqSChGnzTZbkq7lkhc0yd96Yk',
    appId: '1:974085623091:ios:9b01dac4de3616ed520246',
    messagingSenderId: '974085623091',
    projectId: 'speezyyeni',
    storageBucket: 'speezyyeni.firebasestorage.app',
    iosBundleId: 'com.example.speezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDowPQjgrSe4KzrBQCGYzQwTrDbNwQXBus',
    appId: '1:974085623091:web:1ed7fa5adb82aad1520246',
    messagingSenderId: '974085623091',
    projectId: 'speezyyeni',
    authDomain: 'speezyyeni.firebaseapp.com',
    storageBucket: 'speezyyeni.firebasestorage.app',
  );
}
